name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: Install Dependencies
        run: |
          cd web-app
          npm ci
      - name: Build App
        run: |
          cd web-app
          npm run build
